export const loggedInLit = 'loggedIn'
export const usernameLit = 'username'
export const repoLit = 'repo'
export const branchLit = 'branch'
export const commitMsgLit = 'commit_message'
export const dbLit = 'database'
export const dbNameLit = 'receptari.db'
export const dbURLLit = 'not_an_url.example'
